### ISSUE TITLE
Parameter to consider or not @exclude

### ISSUE THREAD

**Issue by soraiareis** [estan/protoc-gen-doc#13]
I have a suggestion of feature. In our case we need to generate internal (developers) and external (clients) documents. For internal, we need a documentation with all messages and atributes (not consider @exclude). But for clientes, we need a documentation without some messages (consider @exclude).

My suggestion is to have a parameter when generating the documents where I inform to consider or not @exclude.

**Comment by estan** [comment]
This is a good suggestion. However, I'm a bit hesitant to add more options to the already quite complicated `--doc_out` format. The problem is that the part preceding the colon (`:`) in the single `--doc_out` parameter is the only way to pass information to the plugin from command line (due to how the plugin API works), and it's kind of hard to stuff a good readable format into it.

I am however alreadly considering adding another way of invoking the plugin:

    --doc_out=<CONFIG_FILENAME>,<OUT_FILENAME>:<OUT_DIR>

where `CONFIG_FILENAME` is a JSON file with various options (output format, possibly the location of a file containing a header for the entire documentation, et.c.). This would then be a good place to put an `enable_exclusions` option like you describe.

When I have time to add this new way of invoking the plugin, I'll try to also implement your suggestion, since it should be quite easy.

**Comment by estan** [comment]
I haven't had time to come up with a new way of invoking the plugin, but I've now added an optional `no-exclude` flag to the command line options. You can now do e.g:

     protoc --doc_out=html,index.html,no-exclude:dev-docs proto/*.proto

for your developer docs and

     protoc --doc_out=html,index.html:client-docs proto/*.proto

for your client docs.

**Comment by soraiareis** [comment]
Thank you! I will test it!

--
*Soraia Reis Fernandes*
