### ISSUE TITLE
Scalar Value Types section

### ISSUE THREAD

**Issue by ornatwork** [estan/protoc-gen-doc#137]
Is it possible to add a flag to the generation in terms of the "Scalar Value Types" section.  For us we are only interested in C# and Javascript types.  We are not interested in the default C++, Java, Python types columns.  Or maybe just give the ability of excluding that section altogether if the user isn't interested in seeing it as a footnote.  The first option would be preferable for us as there is value in the information provided.

**Comment by estan** [comment]
Hi,

The tool currently only has table data for C++, Java and Python, since that's what was available in the table "Scalar Value Types" table in the documentation [1] when I first wrote the tool. I see that they've now added a column for Go which I should probably incorporate. There's no column for C# or JavaScript though (I think since they are not official implementations), and I think I'll have the tool stick to just using what is listed in the official docs.

In any case, there are a couple of options for you:

1. To drop the table all together, use a custom Mustache template. You can just take the built-in template you're using and modify it (remove the table at the bottom). The built-in templates are in the `templates` directory. See README.md for how to specify your custom template instead of using a built-in one. You don't have to rebuild the tool from source to do this.

2. If you want to create your own table with columns for C# and JavaScript, you can either
 * Modify `templates/scalar_value_types.json`, adding your own sections for C# and JavaScript, rebuild the tool (since the `scalar_value_types.json` is embedded in the executable), then use a custom template as described above. In your custom template you would instead modify the table to use the data you added to `scalar_value_types.json`. The keys you used in the JSON file will be available as variables in the template.
 * Or even easier: Just hard code whatever table you want right into your custom template.

Don't hesitate to ask if something is unclear!

**Comment by estan** [comment]
Personally, I would just copy the built-in template you're using, e.g. `html.mustache` -> `custom-html.mustache`, hard code the table to look like what you want, and then use e.g.

    protoc --doc_out=/path/to/custom-html.mustache,index.html:doc proto/*.proto

to generate the docs instead of

    protoc --doc_out=html,index.html:doc proto/*.proto

Since that's the easiest route.

**Comment by ornatwork** [comment]
Sounds good, that will work for me.  Thanks !
