### ISSUE TITLE
Add support for RPC services

### ISSUE THREAD

**Issue by lipnitsk** [estan/protoc-gen-doc#14]
The following `.proto` (assuming `FooRequest` and `FooResponse` are defined) does not appear to generate any documentation today. I can try looking at implementing it once I understand the code a little better.

```proto
service FooService {
	rpc FooMethod (FooRequest) returns (FooResponse);
}
```

The `service` keyword is described on the Google page for [proto2](https://developers.google.com/protocol-buffers/docs/proto#services) or [proto3](https://developers.google.com/protocol-buffers/docs/proto3#services)

**Comment by estan** [comment]
That would be fantastic. Services is one thing I left out when I first wrote the tool, since I wasn't using them myself, but it would be great to have them supported.

Support for this would be added by:

1. Adding a new method `addService` which takes a [ServiceDescriptor](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor#ServiceDescriptor) and a `QVariantList *` as parameters, which parses the information from the `ServiceDescriptor` and adds it to the `QVariantList *`, you could look at the existing `addEnum` for inspiration.
2. Modifying `addFile` to iterate the `ServiceDescriptor`s in the `FileDescriptor`, accumulating the parsed `ServiceDescriptors` in a `QVariantList`, then add that list under a new key "services".
3. Updating the built-in templates in `templates/*.mustache`.

I just started a new job and don't think I'll have time for this myself, but would of course review such a PR if you could make one!

**Comment by estan** [comment]
The `addService` function would make use of a new `addMethod` that works similarly with a `MethodDescriptor` to parse the information about a single RPC method.

We could add support for documenting method parameters and return value á la Doxygen (`@param` and `@return`), but for a first version I would be fine with just a plain text description of the method being supported.

I can do the updating of `README.md`, the examples and the wiki page on custom templates BTW.

**Comment by murph0** [comment]
Had a crack at adding support for RPC services based on your outline. The output is just a simple table with columns for method name, request, response and description. This could be enhanced to produce more of a Doxygen style expanded output with the use of (`@param` and `@return`) as suggested. The docbook and markdown templates will need checking but HTML output is working well.

**Comment by estan** [comment]
Many thanks! Merged.

**Comment by estan** [comment]
I updated the example outputs in `examples/doc` and the wiki page on [custom templates](https://github.com/estan/protoc-gen-doc/wiki/Custom-Templates) to reflect the changes.
