### ISSUE TITLE
Support Markdown formatted comments

### ISSUE THREAD

**Issue by stefan-bengtsson** [estan/protoc-gen-doc#16]
What about adding support for markdown (md or similar) formatted comments in the proto files?

**Comment by estan** [comment]
Hi Stefan,

The problem is that the tool supports arbitrary output formats. The user is free to use their own output format based on a custom Mustache template. The code is completely output format agnostic.

If I would introduce an option to parse the documentation comments as Markdown, and then do special handling of the built-in output formats (HTML, DocBook and Markdown) to transform the Markdown to these formats, the code would be much more complex.

What you can do right now is of course to use Markdown in the comments, and it will work if you use Markdown as output format, since the tool just passes the contents of the comments into the output unchanged, You could then take the produced Markdown and transform it further to some other format (HTML, PDF et.c.) using an appropriate tool.

But I'm afraid that having this tool do Markdown processing is out of scope. Someone else might prefer reStructuredText, or Doxygen-like syntax, or something else.

**Comment by estan** [comment]
To clarify, with this `test.proto`:

```protobuf
/**
 * This is my file. Here's a list:
 *
 * * Foo
 * * Bar
 * * Baz
 *
 * And some **bold** text.
 */

/**
 * A little message, remember to specify `bar`.
 */
message Foo {
  optional int32 foo = 1;
  required string bar = 2;
}
```

you can run:

    protoc --doc_out=markdown,test.md:. test.proto

to get `test.md`:

```markdown
# Protocol Documentation
<a name="top"/>

## Table of Contents
* [test.proto](#test.proto)
 * [Foo](#Foo)
* [Scalar Value Types](#scalar-value-types)

<a name="test.proto"/>
<p align="right"><a href="#top">Top</a></p>

## test.proto

This is my file. Here's a list:

* Foo
* Bar
* Baz

And some **bold** text.

<a name="Foo"/>
### Foo
A little message, remember to specify `bar`.

| Field | Type | Label | Description |
| ----- | ---- | ----- | ----------- |
| foo | [int32](#int32) | optional |  |
| bar | [string](#string) | required |  |






<a name="scalar-value-types"/>
## Scalar Value Types

| .proto Type | Notes | C++ Type | Java Type | Python Type |
| ----------- | ----- | -------- | --------- | ----------- |
| <a name="double"/> double |  | double | double | float |
| <a name="float"/> float |  | float | float | float |
| <a name="int32"/> int32 | Uses variable-length encoding. Inefficient for encoding negative numbers – if your field is likely to have negative values, use sint32 instead. | int32 | int | int |
| <a name="int64"/> int64 | Uses variable-length encoding. Inefficient for encoding negative numbers – if your field is likely to have negative values, use sint64 instead. | int64 | long | int/long |
| <a name="uint32"/> uint32 | Uses variable-length encoding. | uint32 | int | int/long |
| <a name="uint64"/> uint64 | Uses variable-length encoding. | uint64 | long | int/long |
| <a name="sint32"/> sint32 | Uses variable-length encoding. Signed int value. These more efficiently encode negative numbers than regular int32s. | int32 | int | int |
| <a name="sint64"/> sint64 | Uses variable-length encoding. Signed int value. These more efficiently encode negative numbers than regular int64s. | int64 | long | int/long |
| <a name="fixed32"/> fixed32 | Always four bytes. More efficient than uint32 if values are often greater than 2^28. | uint32 | int | int |
| <a name="fixed64"/> fixed64 | Always eight bytes. More efficient than uint64 if values are often greater than 2^56. | uint64 | long | int/long |
| <a name="sfixed32"/> sfixed32 | Always four bytes. | int32 | int | int |
| <a name="sfixed64"/> sfixed64 | Always eight bytes. | int64 | long | int/long |
| <a name="bool"/> bool |  | bool | boolean | boolean |
| <a name="string"/> string | A string must always contain UTF-8 encoded or 7-bit ASCII text. | string | String | str/unicode |
| <a name="bytes"/> bytes | May contain any arbitrary sequence of bytes. | string | ByteString | str |
```

which of course contain the embedded Markdown formatting unchanged, and will thus be rendered like:

# Protocol Documentation
<a name="top"/>

## Table of Contents
* [test.proto](#test.proto)
 * [Foo](#Foo)
* [Scalar Value Types](#scalar-value-types)

<a name="test.proto"/>
<p align="right"><a href="#top">Top</a></p>

## test.proto

This is my file. Here's a list:

* Foo
* Bar
* Baz

And some **bold** text.

<a name="Foo"/>
### Foo
A little message, remember to specify `bar`.

| Field | Type | Label | Description |
| ----- | ---- | ----- | ----------- |
| foo | [int32](#int32) | optional |  |
| bar | [string](#string) | required |  |






<a name="scalar-value-types"/>
## Scalar Value Types

| .proto Type | Notes | C++ Type | Java Type | Python Type |
| ----------- | ----- | -------- | --------- | ----------- |
| <a name="double"/> double |  | double | double | float |
| <a name="float"/> float |  | float | float | float |
| <a name="int32"/> int32 | Uses variable-length encoding. Inefficient for encoding negative numbers – if your field is likely to have negative values, use sint32 instead. | int32 | int | int |
| <a name="int64"/> int64 | Uses variable-length encoding. Inefficient for encoding negative numbers – if your field is likely to have negative values, use sint64 instead. | int64 | long | int/long |
| <a name="uint32"/> uint32 | Uses variable-length encoding. | uint32 | int | int/long |
| <a name="uint64"/> uint64 | Uses variable-length encoding. | uint64 | long | int/long |
| <a name="sint32"/> sint32 | Uses variable-length encoding. Signed int value. These more efficiently encode negative numbers than regular int32s. | int32 | int | int |
| <a name="sint64"/> sint64 | Uses variable-length encoding. Signed int value. These more efficiently encode negative numbers than regular int64s. | int64 | long | int/long |
| <a name="fixed32"/> fixed32 | Always four bytes. More efficient than uint32 if values are often greater than 2^28. | uint32 | int | int |
| <a name="fixed64"/> fixed64 | Always eight bytes. More efficient than uint64 if values are often greater than 2^56. | uint64 | long | int/long |
| <a name="sfixed32"/> sfixed32 | Always four bytes. | int32 | int | int |
| <a name="sfixed64"/> sfixed64 | Always eight bytes. | int64 | long | int/long |
| <a name="bool"/> bool |  | bool | boolean | boolean |
| <a name="string"/> string | A string must always contain UTF-8 encoded or 7-bit ASCII text. | string | String | str/unicode |
| <a name="bytes"/> bytes | May contain any arbitrary sequence of bytes. | string | ByteString | str |

But the tool will do no processing of Markdown when the output format is something else, as it would need `N` ways to convert Markdown to the `N` different output formats (and `N` is unlimited since the user may use a completely custom output format).

**Comment by stefan-bengtsson** [comment]
Hi Estan,
Thanks a lot for your fast response -- the approach you propose should work pretty well for my use case. Thanks for pointing me in that direction!

**Comment by estan** [comment]
No problem. Hope it works out.

**Comment by stefan-bengtsson** [comment]
Hi,
Well, it kind of works, but it is clunky to have to prefix each line with stars to keep indentation (and markdown lines actually starting with a star to keep that).

Example proto:
```
/**
**Bold statement***.  Indented list:

1. First
    1. First / first
    1. First / Second
1. Second
    - Second / First
    - Second / Second
        - Second / Third / First
*/
message Foo {
    optional int32 foo = 1; /// Great field -- great comment!
}
```

Ends up with this markdown

# Protocol Documentation
<a name="top"/>

## Table of Contents
* [test_list.proto](#test_list.proto)
 * [Foo](#Foo)
* [Scalar Value Types](#scalar-value-types)

<a name="test_list.proto"/>
<p align="right"><a href="#top">Top</a></p>

## test_list.proto

<a name="Foo"/>
### Foo
*Bold statement***.  Indented list:

1. First
1. First / first
1. First / Second
1. Second
- Second / First
- Second / Second
- Second / Third / First

| Field | Type | Label | Description |
| ----- | ---- | ----- | ----------- |
| foo | [int32](#int32) | optional | Great field -- great comment! |

**Comment by stefan-bengtsson** [comment]
Are there any better options today than to prefix each line with a star? If not, something that could be done without making the code too complex?

This works as expected, obviously:

```
/**
 * **Bold statement***.  Indented list:
 *
 * 1. First
 *    1. First / first
 *    1. First / Second
 * 1. Second
 *     - Second / First
 *    - Second / Second
 *        - Second / Third / First
 */
message Foo2 {
    optional int32 foo = 1; /// Great field -- great comment!
}
```

<a name="Foo2"/>
### Foo2
**Bold statement***.  Indented list:

1. First
   1. First / first
   1. First / Second
1. Second
    - Second / First
   - Second / Second
       - Second / Third / First

| Field | Type | Label | Description |
| ----- | ---- | ----- | ----------- |
| foo | [int32](#int32) | optional | Great field -- great comment! |

**Comment by estan** [comment]
I understand your frustration, but the tool relies on the protobuf compiler library to do the heavy lifting when it comes to parsing (that's why it's written as a compiler plugin), including the initial parsing of comments. It seems this library will strip leading whitespace from lines inside multi-line comments, unless they begin with "* ".

So there's really nothing I can do about that, short of re-writing the tool completely to do its own parsing of comments. The whitespace has already been stripped by the library by the time the tool gets a hold of it.

That being said, the

```cpp
/**
 * Foo bar
 * baz
 */
```

style is the absolutely most common one used in JavaDoc/Doxygen comments (e.g. used in Qt, KDE, the Java standard library et.c.), which were the inspiration for this tool, and I would recommend sticking to that convention, despite the extra typing. My editor (Vim) will insert the "* " automatically for subsequent lines if I begin a comment with `/**<Enter>`. Perhaps your editor can be configured to do the same?

**Comment by stefan-bengtsson** [comment]
Hi, I personally use vi -- but not necessarily the ones supposed to document the proto files ;-) Anyway, I really appreciate your fast responses and great ideas! 
Thanks /Stefan

**Comment by estan** [comment]
Lugnt :)

**Comment by stefan-bengtsson** [comment]
Man tackar ;-)
