### ISSUE TITLE
any chance to support asciidoc output?

### ISSUE THREAD

**Issue by mhaberler** [estan/protoc-gen-doc#168]
we'd want to integrate the docs into a jekyll-asciidoctor generated website

maybe HTML works as a stopgap

**Comment by estan** [comment]
Hi Michael,

I'm unfortunately a bit too busy at work at the moment, but you should be able to write your own `asciidoc.mustache` custom template without much trouble. Have a look at [Custom Templates](https://github.com/estan/protoc-gen-doc/wiki/Custom-Templates) in the Wiki to make your own output templates.

Let's keep this issue open though no matter what though, since it's a good wish.

**Comment by estan** [comment]
You could also look at the built-in `.mustache` templates as examples. They are in the [templates](https://github.com/estan/protoc-gen-doc/tree/master/templates) directory in the repo.

**Comment by mhaberler** [comment]
@estan great - thanks, that should get us on track!

**Comment by mhaberler** [comment]
mission accomplished - closing
