### ISSUE TITLE
Order of messages

### ISSUE THREAD

**Issue by sumancholleti** [estan/protoc-gen-doc#272]
Looks like by default  generated html is using alphabetical order  to display messages, is there any way to follow proto file order instead?

**Comment by estan** [comment]
No, there's unfortunately no way to control the order of the `file_messages` array, it's always alphabetically ordered (see https://github.com/estan/protoc-gen-doc/wiki/Custom-Templates under "Array Order Guarantees").

I don't want to change the order since users are probably relying on the current order. If you want to, you can always comment out the following line in `main.cpp`:

```cpp
std::sort(messages.begin(), messages.end(), &longNameLessThan);
```

I think (but I'm not sure), that the messages will then be in the order they are declared in the `.proto` file. But this is up to the protobuf library, so if it doesn't work (e.g. the library reports messages in arbitrary order), then there's nothing the plugin can do about it :/ You'll just have to try to see.

**Comment by sumancholleti** [comment]
okay , thanks. So i need to comment that and rebuild right?

**Comment by estan** [comment]
Exactly.

**Comment by christianloth** [comment]
I looked for this string and the file in the whole repo and couldn't find it. Is it still there? I'm trying to figure out how I can generate a doc non-alphabetically 4 years later lol.
