### ISSUE TITLE
enums in a same order

### ISSUE THREAD

**Issue by sumancholleti** [estan/protoc-gen-doc#273]
Hello,

is there any way that i can display enums under every message not like a separate sections

like message1 and its enums, messag2 and its enums

right now its like messag1,message2 and all enums

**Comment by estan** [comment]
No, not without changing the code. It would be possible to change the code such that messages have a list of their nested enums (but remember that there are global enums as well). But I don't want to do this change because there are many people using the plugin with their custom templates at the moment, and it would break their expectations.

The changes to the code would not be too complicated, so if you want to you can always make a fork.

**Comment by estan** [comment]
In general: It's not possible to change the structure documented at https://github.com/estan/protoc-gen-doc/wiki/Custom-Templates#template-input-data-format without changing the code. But if you know C++, it's not too hard to customize the plugin code to generate another structure.

**Comment by sumancholleti** [comment]
I will try, i am not very good with c++

one more question

how do i avoid .proto for id's because jquery is not working if there is .proto or . in id

**Comment by sumancholleti** [comment]
I think i figured this(how do i avoid .proto for id's because jquery is not working if there is .proto or . in id) out thanks.

do we have any edited c++ for above request

**Comment by estan** [comment]
No, there's no C++, what I meant is that if you want this, you'll have to modify the C++ code on your own.

**Comment by sumancholleti** [comment]
yeah am afraid I may not be able to do that because am not a cpp developer , Any clues or hints in that file would be appreciated

**Comment by sumancholleti** [comment]
please let me know if you can help me with custom order for enums like message1-enum,messag2 -enum This would help me greatly

**Comment by sumancholleti** [comment]
okay thanks
